In [1]:
import pandas as pd

## Comment marche le fichier?

1- On importe le fichier excel puis on vérifie le tail, pour voir là où on s'est arrêté

2- On recommence à compléter le tableau avec la fonction de vérification

In [2]:
df = pd.read_excel('bd1.xlsx')
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
63,2022-02-28 00:00:00,DAN,Gueu Zodgeu Wilfried Arnaud,DAN Gueu Zodgeu Wilfried Arnaud,NaN,Impact du service crédit immobilier au sein de...,Banque et assurance,Banque et assurane,Banque et assurane,BOA,N'GRATTIER Antoinne,NaN,NaN
64,2022-02-28 00:00:00,ADDAI,Kouassi Yves Aimé,ADDAI Kouassi Yves Aimé,NaN,contribution du recouvrement des primes impayé...,Banque et assurance,Banque et assurance,Banque et assurance,NaN,SABGARE Tchetien,NaN,NaN
65,2022-03-03 00:00:00,DADIE,Chiadon Cindy Roxane,DADIE Chiadon Cindy Roxane,NaN,Effet du développement financier et de la cons...,économie du développement,économie du développement,économie du développement,NaN,AKA Brou Emmanuel,NaN,NaN
66,2022-09-29 00:00:00,AMU,Koffi Franck Junior,AMU Koffi Franck Junior,767469615.0,Amélioration e la productivité de la force de ...,Banque et assurance,Banque et assurance,Banque et assurance,Nsia Assurance,GRATIER ANTOINNE,NaN,NaN
67,2022-09-29 00:00:00,BLEOUE,Mango Jean Baptiste,BLEOUE Mango Jean Baptiste,NaN,Analyse de la performance d'un regime d'assura...,Audit et Contrôle,Audit et Contrôle,Audit et Contrôle,CFPM,GRATIER ANTOINNE,NaN,NaN

In [3]:
def ajouter_these(df, nom, prenom, impertant, contact, theme, thematique, domaine, filiere, entite, directeur, date_depot, date_soutenance, mentions):
    """
    Ajoute une nouvelle thèse au DataFrame.
    
    Args:
        df (pd.DataFrame): DataFrame à modifier
        impertant (str): Nom de l'impétrant
        contact (str): Contact (email/téléphone)
        theme (str): Thème de la thèse
        thematique (str): Thématique
        domaine (str): Domaine de recherche
        filiere (str): Filière
        entite (str): Entité de rattachement
        directeur (str): Directeur de thèse
        date_depot (str): Date de dépôt (format JJ/MM/AAAA ou AAAA-MM-JJ)
        date_soutenance (str): Date de soutenance (format JJ/MM/AAAA ou AAAA-MM-JJ)
        mentions (str): Mentions spéciales
    
    Returns:
        pd.DataFrame: DataFrame mis à jour
    """
    nouvelle_ligne = {
        "Date de dépôt": pd.to_datetime(date_depot, dayfirst=True),
        "Nom": nom,
        "Prenom": prenom,
        "Impétrant": impertant,
        "Contact": contact,
        "Thème": theme,
        "Thématique": thematique,
        "Domaine": domaine,
        "Filière": filiere,
        "Entité": entite,
        "Directeur": directeur,
        "Date de soutenance": pd.to_datetime(date_soutenance, dayfirst=True),
        "Mentions": mentions
    }
    
    return pd.concat([df, pd.DataFrame([nouvelle_ligne])], ignore_index=True)

In [4]:
df = ajouter_these(
    df=df,
    nom="KOUASSI",
    prenom="Louis Gerard",
    impertant="KOUASSI Louis Gerard",
    contact="0102989154",
    theme="Analyse du plan d'affaire pour l'obtention d'un agrement SFD: Cas de l'appui-conseil à MSF-SA",
    thematique="Audit et Controle",
    domaine="Audit et Controle",
    filiere="Audit et Controle",
    entite="MSF-SA",
    directeur="BADINI Haoua",
    date_depot="10/10/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="Adjey",
    prenom="N'Dah Henri-Jacques",
    impertant="Adjey N'Dah Henri-Jacques",
    contact="",
    theme="Evaluation du dispositif de contrôle interne des immobilisation d'une entreprise industrielle X",
    thematique="Audit et Controle",
    domaine="Audit et Controle",
    filiere="Audit et Controle",
    entite="",
    directeur="APKA Jacques",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KONAN ",
    prenom="Atse Franck Désiré",
    impertant="KONAN  Atse Franck Désiré",
    contact="0787347707",
    theme="Dévoloppement financier et croissance économique: cas de la Côte d'Ivoire",
    thematique="Economie de développement",
    domaine="Economie de développement",
    filiere="Economie de développement",
    entite="",
    directeur="AKA Brou",
    date_depot="10/10/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="MOBIO",
    prenom="Adja Axel Prince Yvon",
    impertant="MOBIO Adja Axel Prince Yvon",
    contact="0141583425",
    theme="Efficacité technique des producteurs de riz dans la région du Gôh: cas du département",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="Aka Brou",
    date_depot="10/10/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KONE",
    prenom="Alligué Samirah Angela Mauricette",
    impertant="KONE Alligué Samirah Angela Mauricette",
    contact="0758422493",
    theme="Effets des TIC du développement financier  et la consommation d'énergies rénouvables sur les émissions de CO2 en CI",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="AKA Brou",
    date_depot="10/10/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
0,2020-10-19 00:00:00,NITIEMA,Wondpagnande Marceline,NITIEMA Wondpagnande Marceline,NaN,Mise en place d'une comptablité générale dans ...,comptabilité,Audit,Audit et contrôle,EPN Alpha,NaN,2020-11-11 00:00:00,Très Bien
1,2020-10-19 00:00:00,EVILARO,Grâce Ursula Aye,EVILARO Grâce Ursula Aye,NaN,Audit interne dans la performance finiancère d...,audit,Audit,Audit et contrôle,SIDAM-CI S.A,NaN,2020-11-11 00:00:00,Bien
2,2020-10-16 00:00:00,WABULASA,Kyalemaninwa Faustin,WABULASA Kyalemaninwa Faustin,NaN,Mise à jour du manuel de procédures de cycle d...,Comptabilité,Comptabilité,Audit et contrôle,caritas CI,NaN,2020-12-22 00:00:00,Bien
3,2020-10-16 00:00:00,NDIAYE,Fatou Raissa Inny Immaculee,NDIAYE Fatou Inny Immaculee,NaN,Evaluation du contrôle interne au niveau du cy...,audit,Audit et contrôle,Audit et contrôle,epsilon,NaN,2020-12-22 00:00:00,Très Bien
4,2020-12-01 00:00:00,BATIONO,Marie Prudence Karidja,BATIONO Marie Prudence Karidja,NaN,La gestion du risque opérationnel de la caisse...,Comptabilité,Comptabilité,Audit et contrôle,AEB-CI,NaN,2020-12-21 00:00:00,Bien
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,2022-10-10 00:00:00,KOUASSI,Louis Gerard,KOUASSI Louis Gerard,0102989154,Analyse du plan d'affaire pour l'obtention d'u...,Audit et Controle,Audit et Controle,Audit et Controle,MSF-SA,BADINI Haoua,NaN,
69,2022-02-28 00:00:00,Adjey,N'Dah Henri-Jacques,Adjey N'Dah Henri-Jacques,,Evaluation du dispositif de contrôle interne d...,Audit et Controle,Audit et Controle,Audit et Controle,,APKA Jacques,NaN,
70,2022-10-10 00:00:00,KONAN,Atse Franck Désiré,KONAN Atse Franck Désiré,0787347707,Dévoloppement financier et croissance économiq...,Economie de développement,Economie de développement,Economie de développement,,AKA Brou,NaN,
71,2022-10-10 00:00:00,MOBIO,Adja Axel Prince Yvon,MOBIO Adja Axel Prince Yvon,0141583425,Efficacité technique des producteurs de riz da...,économie du développement,économie du développement,économie du développement,,Aka Brou,NaN,
72,2022-10-10 00:00:00,KONE,Alligué Samirah Angela Mauricette,KONE Alligué Samirah Angela Mauricette,0758422493,Effets des TIC du développement financier et ...,économie du développement,économie du développement,économie du développement,,AKA Brou,NaN,

In [5]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="DAN",
    prenom="Gueu Zodgeu Wilfried Arnaud",
    impertant="DAN Gueu Zodgeu Wilfried Arnaud",
    contact="",
    theme="Impact du service crédit immobilier au sein de la BOA Côte d'Ivoire",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="BOA",
    directeur="N'GRATTIER Antoinne",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ADDAI ",
    prenom="Kouassi Yves Aimé",
    impertant="ADDAI Kouassi Yves Aimé",
    contact="",
    theme="contribution du recouvrement des primes impayés à la gestion contractuelle",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="",
    directeur="SABGARE Tchetien",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="DADIE",
    prenom="Chiadon Cindy Roxane",
    impertant="DADIE Chiadon Cindy Roxane",
    contact="",
    theme="Effet du développement financier et de la consommation d'énergie sur la croissance économique des pays de la CEDEAO",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="AKA Brou Emmanuel",
    date_depot="03/03/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="AMU",
    prenom="Koffi Franck Junior",
    impertant="AMU Koffi Franck Junior",
    contact="0767469615",
    theme="Amélioration e la productivité de la force de vente d'une compagnie d'assurance non-vie: cas de NSIA-Assurance-Ci",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="Nsia Assurance",
    directeur="GRATIER ANTOINNE",
    date_depot="29/09/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="BLEOUE",
    prenom="Mango Jean Baptiste",
    impertant="BLEOUE Mango Jean Baptiste",
    contact="",
    theme="Analyse de la performance d'un regime d'assurance d'une mutuelle sociale: Cas du régime MMD du fonds de prévoyance militaire (CFPM)",
    thematique="Audit et Contrôle",
    domaine="Audit et Contrôle",
    filiere="Audit et Contrôle",
    entite="CFPM",
    directeur="GRATIER ANTOINNE",
    date_depot="29/09/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="SINA",
    prenom="Kony Emmanuella Evelyne Lauren Zogbeu",
    impertant="SINA Kony Emmanuella Evelyne Lauren Zogbeu",
    contact="",
    theme="Analyse des déterminants de la satisfaction de la clientèle des particuliers: cas de la BICICI",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="BICICI",
    directeur="N'GRATTIER Antoinne",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="AKOTIA ",
    prenom="Lauraine Berice Anta",
    impertant="AKOTIA  Lauraine Berice Anta",
    contact="",
    theme="Elaboration d'une carte des risques opérationnels liés au cycle vente/clients: cas de BEYO",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BEYO",
    directeur="FOFANA Adom",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="DIABY",
    prenom="Akbar Ismael Vel Yalid",
    impertant="DIABY Akbar Ismael Vel Yalid",
    contact="",
    theme="Impact des Garanties sur l'offre des financements à moyen termes",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="",
    directeur="Sangare Tchetien",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="Cissoko ",
    prenom="Habibou dit Babou",
    impertant="Cissoko Habibou dit Babou ",
    contact="",
    theme="Impact de l'ajustage comptable sur la gestion des risques bancaires: cas de la BMS-CI",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BMS-CI",
    directeur="Sangare Tchetien",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="NSENGIYUNVA",
    prenom="Clément",
    impertant="NSENGIYUNVA Clément",
    contact="",
    theme="Analyse des effets de la covid-19 sur la performance des entreprises du secteur informel",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="KONE Salif",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="SINA",
    prenom="Kony Emmanuella Evelyne Lauren Zogbeu",
    impertant="SINA Kony Emmanuella Evelyne Lauren Zogbeu",
    contact="",
    theme="Analyse des déterminants de la satisfaction de la clientèle des particuliers: cas de la BICICI",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="BICICI",
    directeur="N'GRATTIER Antoinne",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="AKOTIA ",
    prenom="Lauraine Berice Anta",
    impertant="AKOTIA  Lauraine Berice Anta",
    contact="",
    theme="Elaboration d'une carte des risques opérationnels liés au cycle vente/clients: cas de BEYO",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BEYO",
    directeur="FOFANA Adom",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="DIABY",
    prenom="Akbar Ismael Vel Yalid",
    impertant="DIABY Akbar Ismael Vel Yalid",
    contact="",
    theme="Impact des Garanties sur l'offre des financements à moyen termes",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="",
    directeur="Sangare Tchetien",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="Cissoko ",
    prenom="Habibou dit Babou",
    impertant="Cissoko Habibou dit Babou ",
    contact="",
    theme="Impact de l'ajustage comptable sur la gestion des risques bancaires: cas de la BMS-CI",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BMS-CI",
    directeur="Sangare Tchetien",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="NSENGIYUNVA",
    prenom="Clément",
    impertant="NSENGIYUNVA Clément",
    contact="",
    theme="Analyse des effets de la covid-19 sur la performance des entreprises du secteur informel",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="KONE Salif",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df

In [ ]:
df.to_excel("bd1.xlsx", index=False)