In [1]:
import pandas as pd

## Comment marche le fichier?

1- On importe le fichier excel puis on vérifie le tail, pour voir là où on s'est arrêté

2- On recommence à compléter le tableau avec la fonction de vérification

In [2]:
df = pd.read_excel('bd1.xlsx')
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
115,2024-04-04 00:00:00,COULIBALY,Siombin Nangoti Ali,COULIBALY Siombin Nangoti Ali,NaN,Contribution de la cellule de remediaton a la ...,Banque et assurance,Banque et assurance,Banque et assurance,Bridge Bank,SANGARE Tchetchien,NaN,NaN
116,2024-04-04 00:00:00,Agui,Emmanuella,Agui Emmanuella,NaN,Amélioration de la satisfaction client dans le...,Banque et assurance,Banque et assurance,Banque et assurance,BHCI,Sangare Tchetien,NaN,NaN
117,2024-04-04 00:00:00,ABIE,Jeanne,ABIE Jeanne,NaN,Analyse de la mission d'audit des dépenses d'a...,Audit et contrôle,Audit et contrôle,Audit et contrôle,CROU,Sangare Tchetien,NaN,NaN
118,2024-04-04 00:00:00,KOUADIO,Aguely Jean,KOUADIO Aguely Jean,NaN,Evaluation des risques dans une société de Ges...,Audit et contrôle,Audit et contrôle,Audit et contrôle,NaN,Fofana César,NaN,NaN
119,2024-04-04 00:00:00,TRAORE,Chintchon Aminata,TRAORE Chintchon Aminata,NaN,Contribution du contrôle interne à l'améliorat...,Audit et contrôle,Audit et contrôle,Audit et contrôle,NaN,SANGARE Tchétien,NaN,NaN

In [3]:
def ajouter_these(df, nom, prenom, impertant, contact, theme, thematique, domaine, filiere, entite, directeur, date_depot, date_soutenance, mentions):
    """
    Ajoute une nouvelle thèse au DataFrame.
    
    Args:
        df (pd.DataFrame): DataFrame à modifier
        impertant (str): Nom de l'impétrant
        contact (str): Contact (email/téléphone)
        theme (str): Thème de la thèse
        thematique (str): Thématique
        domaine (str): Domaine de recherche
        filiere (str): Filière
        entite (str): Entité de rattachement
        directeur (str): Directeur de thèse
        date_depot (str): Date de dépôt (format JJ/MM/AAAA ou AAAA-MM-JJ)
        date_soutenance (str): Date de soutenance (format JJ/MM/AAAA ou AAAA-MM-JJ)
        mentions (str): Mentions spéciales
    
    Returns:
        pd.DataFrame: DataFrame mis à jour
    """
    nouvelle_ligne = {
        "Date de dépôt": pd.to_datetime(date_depot, dayfirst=True),
        "Nom": nom,
        "Prenom": prenom,
        "Impétrant": impertant,
        "Contact": contact,
        "Thème": theme,
        "Thématique": thematique,
        "Domaine": domaine,
        "Filière": filiere,
        "Entité": entite,
        "Directeur": directeur,
        "Date de soutenance": pd.to_datetime(date_soutenance, dayfirst=True),
        "Mentions": mentions
    }
    
    return pd.concat([df, pd.DataFrame([nouvelle_ligne])], ignore_index=True)

In [4]:
df = ajouter_these(
    df=df,
    nom="ADJEHI",
    prenom="N'Tah Carine",
    impertant="ADJEHI N'Tah Carine",
    contact="",
    theme="Contribution de l'audit légal à la performance organisationnelle et financière des entreprises: Cas de la société HAMA",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="HAMA",
    directeur="FOFANA Adom",
    date_depot="05/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="AHOUTY",
    prenom="Tekia",
    impertant="AHOUTY Tekia",
    contact="",
    theme="Impact des investissements directs étrangers sur l'environnement en Côte d'Ivoire",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="KOUADIO Benié",
    date_depot="12/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ZANKOU",
    prenom="Nathalie",
    impertant="ZANKOU Nathalie",
    contact="",
    theme="Contribution de la gestion des risques organisationnels à la bonne gouvernance des institutions: Cas de CARITAS CI",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="CARITAS CI",
    directeur="SANGARE Tchetien",
    date_depot="26/06/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KOMENAN",
    prenom="Jean Marie Vianey",
    impertant="KOMENAN Jean Marie Vianey",
    contact="",
    theme="La commercialisation des produits dans une micro-assurance: cas de l'UNACOOPEC-CI",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="",
    directeur="DOMOA Danielle",
    date_depot="08/07/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="DIOKE Djedjoro",
    prenom="Djedjoro Antoinnette",
    impertant="DIOKE Djedjoro Antoinnette",
    contact="0779968672",
    theme="Impact de la digitalisation des produits et services bancaires sur la relation client: Cas de BOA-CI",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="BOA-CI",
    directeur="N'DRI Yachine",
    date_depot="10/07/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
120,2024-04-05 00:00:00,ADJEHI,N'Tah Carine,ADJEHI N'Tah Carine,,Contribution de l'audit légal à la performance...,Audit et contrôle,Audit et contrôle,Audit et contrôle,HAMA,FOFANA Adom,NaN,
121,2024-04-12 00:00:00,AHOUTY,Tekia,AHOUTY Tekia,,Impact des investissements directs étrangers s...,économie du développement,économie du développement,économie du développement,,KOUADIO Benié,NaN,
122,2024-06-26 00:00:00,ZANKOU,Nathalie,ZANKOU Nathalie,,Contribution de la gestion des risques organis...,Banque et assurance,Banque et assurane,Banque et assurane,CARITAS CI,SANGARE Tchetien,NaN,
123,2024-07-08 00:00:00,KOMENAN,Jean Marie Vianey,KOMENAN Jean Marie Vianey,,La commercialisation des produits dans une mic...,Banque et assurance,Banque et assurane,Banque et assurane,,DOMOA Danielle,NaN,
124,2024-07-10 00:00:00,DIOKE Djedjoro,Djedjoro Antoinnette,DIOKE Djedjoro Antoinnette,0779968672,Impact de la digitalisation des produits et se...,Banque et assurance,Banque et assurane,Banque et assurane,BOA-CI,N'DRI Yachine,NaN,

In [5]:
df.to_excel("bd1.xlsx", index=False)

In [6]:
df = ajouter_these(
    df=df,
    nom="KOUADIO",
    prenom="Kouassi Samuel",
    impertant="KOUADIO Kouassi Samuel",
    contact="",
    theme="Audit des opérations de change à l'international et geston du risque de change: cas d'ECOBANK",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="ECOBANK",
    directeur="N'DRI Yachine",
    date_depot="10/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="YAO",
    prenom="Amoin Ble Myrlène Shiva",
    impertant="YAO Amoin Ble Myrlène Shiva",
    contact="0777826517",
    theme="Effet de l'implémentation du logiciel ODOO sur les résultats comptables de MOYE SARL: Une étude exploratoire",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="MOYE SARL",
    directeur="N'GUESSAN Simon",
    date_depot="10/07/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="GAYE",
    prenom="Mariama",
    impertant="GAYE Mariama",
    contact="0707381952",
    theme="Analyse du processus d'octroi de crédits aux PME: cas de la banque populaire",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="Banque populaire",
    directeur="N'GUESSAN Simon",
    date_depot="10/07/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="COMPAORE",
    prenom="Boris Cedric",
    impertant="COMPAORE Doris Cedric",
    contact="0777282902",
    theme="Analyse de la relation entre les caractéristiques des particuliers et les impayés",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="",
    directeur="N'DRI Yachine",
    date_depot="10/07/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ELEMEHA",
    prenom="Danielle-Esther",
    impertant="ELEMEHA Danielle-Esther",
    contact="0749836044",
    theme="Conquête et fidélisation de la clientèle retraitée d'une microfinance: cas du fonds international pour le développement de la retraite active FIDRA",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="FIDRA",
    directeur="DOMOA Daniel",
    date_depot="03/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
125,2024-04-10 00:00:00,KOUADIO,Kouassi Samuel,KOUADIO Kouassi Samuel,,Audit des opérations de change à l'internation...,Banque et assurance,Banque et assurane,Banque et assurane,ECOBANK,N'DRI Yachine,NaN,
126,2024-07-10 00:00:00,YAO,Amoin Ble Myrlène Shiva,YAO Amoin Ble Myrlène Shiva,0777826517,Effet de l'implémentation du logiciel ODOO sur...,Audit et contrôle,Audit et contrôle,Audit et contrôle,MOYE SARL,N'GUESSAN Simon,NaN,
127,2024-07-10 00:00:00,GAYE,Mariama,GAYE Mariama,0707381952,Analyse du processus d'octroi de crédits aux P...,Banque et assurance,Banque et assurane,Banque et assurane,Banque populaire,N'GUESSAN Simon,NaN,
128,2024-07-10 00:00:00,COMPAORE,Boris Cedric,COMPAORE Doris Cedric,0777282902,Analyse de la relation entre les caractéristiq...,Banque et assurance,Banque et assurane,Banque et assurane,,N'DRI Yachine,NaN,
129,2024-04-03 00:00:00,ELEMEHA,Danielle-Esther,ELEMEHA Danielle-Esther,0749836044,Conquête et fidélisation de la clientèle retra...,Banque et assurance,Banque et assurane,Banque et assurane,FIDRA,DOMOA Daniel,NaN,

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="LOUA",
    prenom="Dervine Anne Elisabeth Gausseu",
    impertant="LOUA Dervine Anne Elisabeth Gausseu",
    contact="",
    theme="L'accessibilité des PME aux financement du marché par les banques: cas de la banque populaire de Côte d'Ivoire",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="banque populaire",
    directeur="N'DRI Yachine",
    date_depot="03/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="FANNY",
    prenom="Inza Ladji Habib",
    impertant="FANNY Inza Ladji Habib",
    contact="",
    theme="Effet de la gouvernance sur la croissance économique en Afrique",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="MOUSSA Kouamé Richard",
    date_depot="03/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="SORO",
    prenom=" Kinignari Zakaria",
    impertant="SORO Kinignari Zakaria",
    contact="",
    theme="Analyse des déterminants des stratégies d'adaptations des riziculteurs face au changements climatique: un exemple de la région du Kabadougou",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="Salif Koné",
    date_depot="03/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="CAMINO",
    prenom="Tanobla Morisson",
    impertant="CAMINO Tanobla Morisson",
    contact="",
    theme="L'influence de la GRC sur la performance financière de la banque: cas de la SIB",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="",
    directeur="SANGARE",
    date_depot="03/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="EKOU",
    prenom="Tanoh Yves Elfried",
    impertant="EKOU Tanoh Yves Elfried",
    contact="",
    theme="Impact du commerce international sur la croissance économique: Rôle de la corruption en Côte d'Ivoire",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="KONE Salif",
    date_depot="03/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="SACOH",
    prenom=" Dorcas",
    impertant="SACOH Dorcas",
    contact="",
    theme="Effets des chocs conjoncturelles sur la banlance commerciale des pays de la CEDEAO",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="ASSOUMOU Ella",
    date_depot="03/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="COULIBALY",
    prenom="Siombin Nangoti Ali",
    impertant="COULIBALY Siombin Nangoti Ali",
    contact="",
    theme="Contribution de la cellule de remediaton a la mise à jour des données clientèles: Cas de la Bridge Bank Group Ci",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="Bridge Bank",
    directeur="SANGARE Tchetchien",
    date_depot="04/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="Agui",
    prenom=" Emmanuella",
    impertant="Agui Emmanuella",
    contact="",
    theme="Amélioration de la satisfaction client dans les établissements bancaires: cas de la BHCI Treichville",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BHCI",
    directeur="Sangare Tchetien",
    date_depot="04/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ABIE",
    prenom="Jeanne",
    impertant="ABIE Jeanne",
    contact="",
    theme="Analyse de la mission d'audit des dépenses d'alimentation dans l'administrationn publique: cas du centre régionale des oeuvres Universitaires",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="CROU",
    directeur="Sangare Tchetien",
    date_depot="04/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KOUADIO",
    prenom="Aguely Jean",
    impertant="KOUADIO Aguely Jean",
    contact="",
    theme="Evaluation des risques dans une société de Gestion Immoilière: Une approche d'audit pour la prévention et la détection des risques de fraudes dans la société Beta",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="Fofana César",
    date_depot="04/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="TRAORE",
    prenom="Chintchon Aminata",
    impertant="TRAORE Chintchon Aminata",
    contact="",
    theme="Contribution du contrôle interne à l'amélioration de la gestion des risques opérationnelles: cas de l'entreprise alpha",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="SANGARE Tchétien",
    date_depot="04/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

In [ ]:
df.to_excel("bd1.xlsx", index=False)