In [1]:
import pandas as pd

## Comment marche le fichier?

1- On importe le fichier excel puis on vérifie le tail, pour voir là où on s'est arrêté

2- On recommence à compléter le tableau avec la fonction de vérification

In [3]:
df = pd.read_excel('bd1.xlsx')
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
181,2025-04-15 00:00:00,MOUNDIN,Moumbagna Aboubakar Sidick,MOUNDIN Moumbagna Aboubakar Sidick,0152240877,Stratégie de conquête des clients par AFGBANK CI,Banque et assurance,Banque et assurance,Banque et assurance,AFGBANK,KONAN Amoin Lucie,NaN,NaN
182,2025-04-15 00:00:00,YABO,Ossondoh Martial,YABO Ossondoh Martial,NaN,Analyse des risques opérationnels bancaires da...,Banque et assurance,Banque et assurance,Banque et assurance,AFG BANK,N'GUESSAN Simon,NaN,NaN
183,2025-04-16 00:00:00,MIAKO,Jean Yves Arnold,MIAKO Jean Yves Arnold,0103926375,Effet de la croissance économique sur les inég...,économie du développement,économie du développement,économie du développement,NaN,ASSOUMOU Giscard,NaN,NaN
184,2025-04-17 00:00:00,GNAMBA,Grâce Juvenal,GNAMBA Grâce Juvenal,NaN,Investissements directs étrangers et croissanc...,économie du développement,économie du développement,économie du développement,NaN,AKA Brou,NaN,NaN
185,2025-04-17 00:00:00,SENY,Mariam Leka,SENY Mariam Leka,0777918656,Mise en place d'un système de pilotage de la p...,Audit et contrôle,Audit et contrôle,Audit et contrôle,GIH-UEMOA,KONAN Lucie,NaN,NaN

In [3]:
def ajouter_these(df, nom, prenom, impertant, contact, theme, thematique, domaine, filiere, entite, directeur, date_depot, date_soutenance, mentions):
    """
    Ajoute une nouvelle thèse au DataFrame.
    
    Args:
        df (pd.DataFrame): DataFrame à modifier
        impertant (str): Nom de l'impétrant
        contact (str): Contact (email/téléphone)
        theme (str): Thème de la thèse
        thematique (str): Thématique
        domaine (str): Domaine de recherche
        filiere (str): Filière
        entite (str): Entité de rattachement
        directeur (str): Directeur de thèse
        date_depot (str): Date de dépôt (format JJ/MM/AAAA ou AAAA-MM-JJ)
        date_soutenance (str): Date de soutenance (format JJ/MM/AAAA ou AAAA-MM-JJ)
        mentions (str): Mentions spéciales
    
    Returns:
        pd.DataFrame: DataFrame mis à jour
    """
    nouvelle_ligne = {
        "Date de dépôt": pd.to_datetime(date_depot, dayfirst=True),
        "Nom": nom,
        "Prenom": prenom,
        "Impétrant": impertant,
        "Contact": contact,
        "Thème": theme,
        "Thématique": thematique,
        "Domaine": domaine,
        "Filière": filiere,
        "Entité": entite,
        "Directeur": directeur,
        "Date de soutenance": pd.to_datetime(date_soutenance, dayfirst=True),
        "Mentions": mentions
    }
    
    return pd.concat([df, pd.DataFrame([nouvelle_ligne])], ignore_index=True)

In [4]:
df = ajouter_these(
    df=df,
    nom="GNAMBA",
    prenom="Grâce Juvenal",
    impertant="GNAMBA Grâce Juvenal",
    contact="",
    theme="Investissements directs étrangers et croissance économique en Côte d'Ivoire",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="AKA Brou",
    date_depot="17/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="SENY",
    prenom="Mariam Leka",
    impertant="SENY Mariam Leka",
    contact="0777918656",
    theme="Mise en place d'un système de pilotage de la performance dans le secteur des paiements: Cas de GIH-UEMOA",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="GIH-UEMOA",
    directeur="KONAN Lucie",
    date_depot="17/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(2)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
184,2025-04-17 00:00:00,GNAMBA,Grâce Juvenal,GNAMBA Grâce Juvenal,,Investissements directs étrangers et croissanc...,économie du développement,économie du développement,économie du développement,,AKA Brou,NaN,
185,2025-04-17 00:00:00,SENY,Mariam Leka,SENY Mariam Leka,0777918656,Mise en place d'un système de pilotage de la p...,Audit et contrôle,Audit et contrôle,Audit et contrôle,GIH-UEMOA,KONAN Lucie,NaN,

In [5]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="SADIE",
    prenom="Yann Michel",
    impertant="SADIE Yann Michel",
    contact="0102638915",
    theme="L'influence d'une éducation financière sur l'amélioration de la bancarisation en Côte d'Ivoire",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="",
    directeur="DOMOA Danielle",
    date_depot="15/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="BREDOU",
    prenom="Assouema Stephanie",
    impertant="BREDOU Assouema Stephanie",
    contact="O709981418",
    theme="La gestion des sinistres liés aux produits d'assurance en banque: cas du produit d'assurance YACONFORT de la SOCIETE GENERALE de Côte d'Ivoire",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="SOCIETE GENERALE",
    directeur="DOMOA Danielle",
    date_depot="15/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="SORO",
    prenom="Daouda Gnekognan",
    impertant="SORO Daouda Gnekognan",
    contact="0747236343",
    theme="Stratégie marketing pour l'accroissement d'une banque: Cas de la BDU-CI",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BDU-CI",
    directeur="KONAN Amoin Lucie",
    date_depot="15/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ASSAMOI ",
    prenom="Akoun Rosemonde Charlene",
    impertant="ASSAMOI  Akoun Rosemonde Charlene",
    contact="0141219134",
    theme="L'importance de l'évaluation des immobilisations corporelles dans la gestion efficace des établissements scolaires privés d'abidjan: cas de ALHPA",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="SANGARE Tchetien",
    date_depot="15/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="N'GUESSAN",
    prenom="Timy Urielle Sephora",
    impertant="N'GUESSAN Timy Urielle Sephora",
    contact="0787831715",
    theme="Evaluation du dispositif de contrôle interne dans les sociétés de gestion et d'intermédiation",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="N'DRI Yachine",
    date_depot="15/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(3)

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="AFOUMOU",
    prenom="Ange Alex",
    impertant="AFOUMOU Ange Alex",
    contact="0556040441",
    theme="L'impact de l'inétgration des nouvelles technologies sur le processus de compensation bancaire: cas de AFG BANK",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="AFG BANK",
    directeur="SANGARE Tchetien",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="BOUADOU-NIDA",
    prenom="Sara Gbocho Eliel",
    impertant="BOUADOU-NIDA Sara Gbocho Eliel",
    contact="0749778822",
    theme="Audit des immobilisations corporelles et la fiabilité de l'information financière: cas de la société LEAD PRODUCT",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="LEAD PRODUCT",
    directeur="OUATTARA Bassife",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="LOGBO",
    prenom="Amakouba Tiffany",
    impertant="LOGBO Amakouba Tiffany",
    contact="0777966985",
    theme="Audit des créances clients dans un établissement de restauration: cas du Restaurant Angola",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="Restaurant Angola",
    directeur="BADINI Haoua",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="TOHOUA",
    prenom="Dekassan Lionel",
    impertant="TOHOUA Dekassan Lionel",
    contact="0789868565",
    theme="La contribution de l'audit externe à la gestion des risques fiscaux: Cas de l'entreprise Delta",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="BADINI Haoua",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="SANOGO",
    prenom="Mohamed Bantche",
    impertant="SANOGO Mohamed Bantche",
    contact="0710806273",
    theme="Elaboration d'un manuel de procédures comptables: cas de l'entreprise X",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="FOFANA Adon",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(2)

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="SETONDJI",
    prenom=" Magloire Gilchrist K.D",
    impertant="SETONDJI Magloire Gilchrist K.D",
    contact="0103547878",
    theme="Audit de projet d'une ONG financée par le fond Américain PEPFAR: Cas de médecins humanistes",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="AHOGNISSO Angeline",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ESMEL",
    prenom="Amari Evrard Ulrich",
    impertant="ESMEL Amari Evrard Ulrich",
    contact="0152521053",
    theme="Evaluation du dispositif de contrôle interne dans la gestion d'une station-service: cas de la station service Bêta de PETRO IVOIRE SA",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="AKA Brou",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KADJO",
    prenom=" Aimée Jocelyne Berthe",
    impertant="KADJO Aimée Jocelyne Berthe",
    contact="0788549653",
    theme="Facteurs explicatifs du Ralentissement dans le traitement de l'information entre agence locale et le siège de SANLAM ALLIANZ: cas de l'agence locale OBE-Live d'Attobant",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="SANLAM ALLIANZ",
    directeur="BEDA Clotaire",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="MOUNDIN",
    prenom="Moumbagna Aboubakar Sidick",
    impertant="MOUNDIN Moumbagna Aboubakar Sidick",
    contact="0152240877",
    theme="Stratégie de conquête des clients par AFGBANK CI",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="AFGBANK",
    directeur="KONAN Amoin Lucie",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="YABO",
    prenom="Ossondoh Martial",
    impertant="YABO Ossondoh Martial",
    contact="",
    theme="Analyse des risques opérationnels bancaires dans un processus des fusions acquisition: cas d'AFG BANK",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="AFG BANK",
    directeur="N'GUESSAN Simon",
    date_depot="15/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="MIAKO",
    prenom="Jean Yves Arnold",
    impertant="MIAKO Jean Yves Arnold",
    contact="0103926375",
    theme="Effet de la croissance économique sur les inégalités de revenus",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="ASSOUMOU Giscard",
    date_depot="16/04/25",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(3)

In [ ]:
df.to_excel("bd1.xlsx", index=False)