In [1]:
import pandas as pd

## Comment marche le fichier?

1- On importe le fichier excel puis on vérifie le tail, pour voir là où on s'est arrêté

2- On recommence à compléter le tableau avec la fonction de vérification

In [2]:
df = pd.read_excel('bd.xlsx')
df

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Theme,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
0,2020-10-19,Nitiema,Wondpagnande Marceline,Nitiema Wondpagnande Marceline,NaN,Mise en place d'une comptablité générale dans ...,comptabilité,Audit,Audit et contrôle,NaN,NaN,2020-11-11,Très Bien
1,2020-10-19,Evilaro,Grâce Ursula Aye,Evilaro Grâce Ursula Aye,NaN,Audit interne dans la performance finiancère d...,audit,Audit,Audit et contrôle,SIDAM-CI S.A,NaN,2020-11-11,Bien
2,2020-10-16,WABULASA,Kyalemaninwa Faustin,WABULASA Kyalemaninwa Faustin,NaN,Mise à jour du manuel de procédures de cycle d...,Comptabilité,Comptabilité,Audit et contrôle,caritas CI,NaN,2020-12-22,Bien
3,2020-10-16,NDIAYE,Fatou Raissa Inny Immaculee,NDIAYE Fatou Inny Immaculee,NaN,Evaluation du contrôle interne au niveau du cy...,audit,Audit et contrôle,Audit et contrôle,NaN,NaN,2020-12-22,Très Bien
4,2020-12-01,BATIONO,Marie Prudence Karidja,BATIONO Marie Prudence Karidja,NaN,La gestion du risque opérationnel de la caisse...,Comptabilité,Comptabilité,Audit et contrôle,AEB-CI,NaN,2020-12-21,Bien
5,2020-12-02,N'GUESSAN,Amenan Laura,N'GUESSAN Amenan Laura,NaN,Audit des comptes fournisseurs d'une société i...,Comptabilité,Comptabilité,Audit et contrôle,NaN,NaN,2020-12-22,Très Bien
6,2020-12-02,KOUAME,Agoh Princess Xena,KOUAME Agoh Princess Xena,NaN,Evaluation du cycle de trésorerie: cas de la s...,audit,Audit et contrôle,Audit et contrôle,SOUMIE,NaN,2020-12-22,Très Bien
7,2020-12-02,KOUAME,Kouassi Yves Herman,KOUAME Agoh Princess Xena,NaN,Analalyse de l'impact de l'extension du reseau...,Assurance,Assurance,Banque et Assurance,NSIA ASSURANCES,NaN,2020-12-21,Bien

In [10]:
def ajouter_these(df, nom, prenom, impertant, contact, theme, thematique, domaine, filiere, entite, directeur, date_depot, date_soutenance, mentions):
    """
    Ajoute une nouvelle thèse au DataFrame.
    
    Args:
        df (pd.DataFrame): DataFrame à modifier
        impertant (str): Nom de l'impétrant
        contact (str): Contact (email/téléphone)
        theme (str): Thème de la thèse
        thematique (str): Thématique
        domaine (str): Domaine de recherche
        filiere (str): Filière
        entite (str): Entité de rattachement
        directeur (str): Directeur de thèse
        date_depot (str): Date de dépôt (format JJ/MM/AAAA ou AAAA-MM-JJ)
        date_soutenance (str): Date de soutenance (format JJ/MM/AAAA ou AAAA-MM-JJ)
        mentions (str): Mentions spéciales
    
    Returns:
        pd.DataFrame: DataFrame mis à jour
    """
    nouvelle_ligne = {
        "Date de dépôt": pd.to_datetime(date_depot, dayfirst=True),
        "Nom": nom,
        "Prenom": prenom,
        "Impétrant": impertant,
        "Contact": contact,
        "Theme": theme,
        "Thématique": thematique,
        "Domaine": domaine,
        "Filière": filiere,
        "Entité": entite,
        "Directeur": directeur,
        "Date de soutenance": pd.to_datetime(date_soutenance, dayfirst=True),
        "Mentions": mentions
    }
    
    return pd.concat([df, pd.DataFrame([nouvelle_ligne])], ignore_index=True)

In [11]:
df = ajouter_these(
    df=df,
    nom="BATIONO",
    prenom="Marie Prudence Karidja",
    impertant="BATIONO Marie Prudence Karidja",
    contact="",
    theme="La gestion du risque opérationnel de la caisse: cas de AEB-CI",
    thematique="Comptabilité",
    domaine="Comptabilité",
    filiere="Audit et contrôle",
    entite="caritas CI",
    directeur="",
    date_depot="01/12/20",  # Format JJ/MM/AAAA
    date_soutenance="2020-12-21",  # Format AAAA-MM-JJ
    mentions="Bien"
)
df = ajouter_these(
    df=df,
    nom="N'GUESSAN",
    prenom="Amenan Laura",
    impertant="N'GUESSAN Amenan Laura",
    contact="",
    theme="Audit des comptes fournisseurs d'une société immobilère: cas de la société ALPHA",
    thematique="Comptabilité",
    domaine="Comptabilité",
    filiere="Audit et contrôle",
    entite="caritas CI",
    directeur="",
    date_depot="02/12/20",  # Format JJ/MM/AAAA
    date_soutenance="2020-12-22",  # Format AAAA-MM-JJ
    mentions="Très Bien"
)
df

C:\Users\HP\AppData\Local\Temp\ipykernel_9836\1554907175.py:34: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  "Date de soutenance": pd.to_datetime(date_soutenance, dayfirst=True),

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Theme,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
0,2020-10-19,Nitiema,Wondpagnande Marceline,Nitiema Wondpagnande Marceline,NaN,Mise en place d'une comptablité générale dans ...,comptabilité,Audit,Audit et contrôle,NaN,NaN,2020-11-11,Très Bien
1,2020-10-19,Evilaro,Grâce Ursula Aye,Evilaro Grâce Ursula Aye,NaN,Audit interne dans la performance finiancère d...,audit,Audit,Audit et contrôle,SIDAM-CI S.A,NaN,2020-11-11,Bien
2,2020-10-16,WABULASA,Kyalemaninwa Faustin,WABULASA Kyalemaninwa Faustin,NaN,Mise à jour du manuel de procédures de cycle d...,Comptabilité,Comptabilité,Audit et contrôle,caritas CI,NaN,2020-12-22,Bien
3,2020-10-16,NDIAYE,Fatou Raissa Inny Immaculee,NDIAYE Fatou Inny Immaculee,NaN,Evaluation du contrôle interne au niveau du cy...,audit,Audit et contrôle,Audit et contrôle,NaN,NaN,2020-12-22,Très Bien
4,2020-12-01,BATIONO,Marie Prudence Karidja,BATIONO Marie Prudence Karidja,,La gestion du risque opérationnel de la caisse...,Comptabilité,Comptabilité,Audit et contrôle,caritas CI,,2020-12-21,Bien
5,2020-12-02,N'GUESSAN,Amenan Laura,N'GUESSAN Amenan Laura,,Audit des comptes fournisseurs d'une société i...,Comptabilité,Comptabilité,Audit et contrôle,caritas CI,,2020-12-22,Très Bien

In [12]:
df.to_excel("bd.xlsx", index=False)