In [17]:
import pandas as pd

## Comment marche le fichier?

1- On importe le fichier excel puis on vérifie le tail, pour voir là où on s'est arrêté

2- On recommence à compléter le tableau avec la fonction de vérification

In [18]:
df = pd.read_excel('bd1.xlsx')
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
89,2023-06-30 00:00:00,OSSEY,Reine Marina Aude,OSSEY Reine Marina Aude,NaN,Contribution de la mise en oeuvre des recomman...,Audit et contrôle,Audit et contrôle,Audit et contrôle,BNETD,FOFANA Adom,NaN,NaN
90,2023-06-30 00:00:00,KOTTY,Kotty Paul Marie,KOTTY Kotty Paul Marie,NaN,Analyse du marché de la téléphonie mobile en C...,économie du développement,économie du développement,économie du développement,NaN,Sangare Tchetien,NaN,NaN
91,2023-07-03 00:00:00,ABIE,Jeanne,ABIE Jeanne,NaN,Analyse de la mission d'audit des dépenses d'a...,Audit et contrôle,Audit et contrôle,Audit et contrôle,CROU,Sangare Tchetien,NaN,NaN
92,2023-07-03 00:00:00,COULIBALY,Myriam,COULIBALY Myriam,NaN,Analyse des risques liés à la gestion du cycle...,Audit et contrôle,Audit et contrôle,Audit et contrôle,TS Immobilier,Fofana César,NaN,NaN
93,2023-07-03 00:00:00,KOBRON,Ehien,KOBRON Ehien,NaN,Evolution de la satisfaction clientèle particu...,Audit et contrôle,Audit et contrôle,Audit et contrôle,BHCI,KOUASSI Rufin Cyriaque,NaN,NaN

In [19]:
def ajouter_these(df, nom, prenom, impertant, contact, theme, thematique, domaine, filiere, entite, directeur, date_depot, date_soutenance, mentions):
    """
    Ajoute une nouvelle thèse au DataFrame.
    
    Args:
        df (pd.DataFrame): DataFrame à modifier
        impertant (str): Nom de l'impétrant
        contact (str): Contact (email/téléphone)
        theme (str): Thème de la thèse
        thematique (str): Thématique
        domaine (str): Domaine de recherche
        filiere (str): Filière
        entite (str): Entité de rattachement
        directeur (str): Directeur de thèse
        date_depot (str): Date de dépôt (format JJ/MM/AAAA ou AAAA-MM-JJ)
        date_soutenance (str): Date de soutenance (format JJ/MM/AAAA ou AAAA-MM-JJ)
        mentions (str): Mentions spéciales
    
    Returns:
        pd.DataFrame: DataFrame mis à jour
    """
    nouvelle_ligne = {
        "Date de dépôt": pd.to_datetime(date_depot, dayfirst=True),
        "Nom": nom,
        "Prenom": prenom,
        "Impétrant": impertant,
        "Contact": contact,
        "Thème": theme,
        "Thématique": thematique,
        "Domaine": domaine,
        "Filière": filiere,
        "Entité": entite,
        "Directeur": directeur,
        "Date de soutenance": pd.to_datetime(date_soutenance, dayfirst=True),
        "Mentions": mentions
    }
    
    return pd.concat([df, pd.DataFrame([nouvelle_ligne])], ignore_index=True)

In [20]:
df = ajouter_these(
    df=df,
    nom="DAGRI",
    prenom="Fleure",
    impertant="DAGRI Fleure",
    contact="",
    theme="Audit du dispositif HSE: cas du BNETD",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="BNETD",
    directeur="FOFANA Andom",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ACHO",
    prenom="Bah Marie Otnielle",
    impertant="ACHO Bah Marie Otnielle",
    contact="",
    theme="Impact du contrôle interne sur la performance financière de l'entreprise: Cas du BNETD",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="BNETD",
    directeur="FOFANA Andom",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="APKA",
    prenom="Agnimel Claude Virgile",
    impertant="APKA Agnimel Claude Virgile",
    contact="",
    theme="Evaluation du contrôle interne du Cycle Achat: Cas de VOLCAGRO-CI",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="VOLCAGRO-CI",
    directeur="FOFANA Andom",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="DOGBO",
    prenom="Bisso Gilles Kevine",
    impertant="DOGBO Bisso Gilles Kevine",
    contact="",
    theme="L'impact du crédit-bail sur la performance financière: Cas de la BICICI",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BICICI",
    directeur="KOUASSI Rufin Cyriaque",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="JOANNY",
    prenom="Tape Waissa Mamita",
    impertant="JOANNY Tape Waissa Mamita",
    contact="",
    theme="Evaluation des procédures du contrôle interne du cycle Achat/Fournisseur dans le cadre d'une mission de CAC: Cas de la SIA",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="FOFANA Andom",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
94,2023-07-03 00:00:00,DAGRI,Fleure,DAGRI Fleure,,Audit du dispositif HSE: cas du BNETD,Audit et contrôle,Audit et contrôle,Audit et contrôle,BNETD,FOFANA Andom,NaN,
95,2023-07-03 00:00:00,ACHO,Bah Marie Otnielle,ACHO Bah Marie Otnielle,,Impact du contrôle interne sur la performance ...,Audit et contrôle,Audit et contrôle,Audit et contrôle,BNETD,FOFANA Andom,NaN,
96,2023-07-03 00:00:00,APKA,Agnimel Claude Virgile,APKA Agnimel Claude Virgile,,Evaluation du contrôle interne du Cycle Achat:...,Audit et contrôle,Audit et contrôle,Audit et contrôle,VOLCAGRO-CI,FOFANA Andom,NaN,
97,2023-07-03 00:00:00,DOGBO,Bisso Gilles Kevine,DOGBO Bisso Gilles Kevine,,L'impact du crédit-bail sur la performance fin...,Banque et assurance,Banque et assurance,Banque et assurance,BICICI,KOUASSI Rufin Cyriaque,NaN,
98,2023-07-03 00:00:00,JOANNY,Tape Waissa Mamita,JOANNY Tape Waissa Mamita,,Evaluation des procédures du contrôle interne ...,Audit et contrôle,Audit et contrôle,Audit et contrôle,,FOFANA Andom,NaN,

In [21]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="OUATTARA",
    prenom="Kra",
    impertant="OUATTARA Kra",
    contact="",
    theme="Impact des dépenses publiques sociales sur la croissance économique en CI",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="KOUAKOU Auguste",
    date_depot="26/01/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="OUATTARA",
    prenom="Abdel Kader",
    impertant="OUATTARA Abdel Kader",
    contact="",
    theme="Contribution à l'amélioration de l'élaboration des états financiers des entités dans le cadre de la mission de visa",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="FOFANA Adom",
    date_depot="28/02/22",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="TANOE",
    prenom="Ahoba Marie-Déirée",
    impertant="TANOE Ahoba Marie-Déirée",
    contact="0767469615",
    theme="Contribution de la revision comptable à la gestion financières et comptable d'une entreprise; cas de COMTRATS",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="COMTRATS",
    directeur="FOFANA Andom",
    date_depot="31/01/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="BLE",
    prenom="Israel Djedje",
    impertant="BLE Israel Djedje",
    contact="",
    theme="La fiscalité comme lévier de développement: cas de la Côte d'Ivoire",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="MOUSSA Kouame Richard",
    date_depot="28/03/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ATTA",
    prenom="N'Doua Jean Christian",
    impertant="ATTA N'Doua Jean Christian",
    contact="",
    theme="Analyse des facteurs limitant la production des éléveurs de porcs de la ville d'Abidjan et ses alentours",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="MOUSSA Kouame Richard",
    date_depot="28/03/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="LAGO",
    prenom="Logblo Olga-Dominique",
    impertant="LAGO Logblo Olga-Dominique",
    contact="",
    theme="Analyse de stratégie de fidélisation des clients de la banque des dépôts du trésor public de Côte d'Ivoire",
    thematique="Banque et assurance",
    domaine="Banque et assurane",
    filiere="Banque et assurane",
    entite="Banque du trésor",
    directeur="SANGARE Tchetien",
    date_depot="04/04/24",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KOUKONI",
    prenom="Gloria Marina",
    impertant="KOUKONI Gloria Marina",
    contact="",
    theme="Conquête et fidélisation de la clientèle, un jeu pour les banques aujour'hui: Cas de la BHCI",
    thematique="Banque et assurance",
    domaine="Banque et assurance",
    filiere="Banque et assurance",
    entite="BHCI",
    directeur="APKESSE",
    date_depot="26/06/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="TRAORE",
    prenom="Cadic Laeticia Ley",
    impertant="TRAORE Cadic Laeticia Ley",
    contact="",
    theme="Finances islamique et inclusion financière",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="MOUSSA Kouamé Richard",
    date_depot="30/06/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="AVY",
    prenom="Sombo Marie-Andrée Eugenie",
    impertant="AVY Sombo Marie-Andrée Eugenie",
    contact="",
    theme="Fracture numérique et transition démographique en Côte d'Ivoire",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="KOUAKOU Auguste",
    date_depot="30/06/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="TIAPANI",
    prenom="Akpa Jean Cyriaque",
    impertant="TIAPANI Akpa Jean Cyriaque",
    contact="",
    theme="Impact de la COVID-19 sur le commerce électronique en Afrique cas de Jumia",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="KOUAKOU Auguste",
    date_depot="30/06/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

In [ ]:
df.to_excel("bd1.xlsx", index=False)

In [ ]:
df = ajouter_these(
    df=df,
    nom="BAMBA",
    prenom=" Awa",
    impertant="BAMBA Awa",
    contact="",
    theme="La mission du commissaire aux comptes dans la certification du cycle vente-client: cas de la société X",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="",
    directeur="SANGARE",
    date_depot="30/06/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="OSSEY",
    prenom="Reine Marina Aude",
    impertant="OSSEY Reine Marina Aude",
    contact="",
    theme="Contribution de la mise en oeuvre des recommandations d'audit interne à l'amélioration du processus de gestion des stocks au BNETD",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="BNETD",
    directeur="FOFANA Adom",
    date_depot="30/06/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KOTTY",
    prenom="Kotty Paul Marie",
    impertant="KOTTY Kotty Paul Marie",
    contact="",
    theme="Analyse du marché de la téléphonie mobile en Côte d'Ivoire:dynamique du marché et performance des opérateurs",
    thematique="économie du développement",
    domaine="économie du développement",
    filiere="économie du développement",
    entite="",
    directeur="Sangare Tchetien",
    date_depot="30/06/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="ABIE",
    prenom="Jeanne",
    impertant="ABIE Jeanne",
    contact="",
    theme="Analyse de la mission d'audit des dépenses d'alimentation dans l'administrationn publique: cas du centre régionale des oeuvres Universitaires",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="CROU",
    directeur="Sangare Tchetien",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="COULIBALY",
    prenom="Myriam",
    impertant="COULIBALY Myriam",
    contact="",
    theme="Analyse des risques liés à la gestion du cycle achats fournisseurs dans le cadre d'une mission de CAC: Cas de l'agence TS Immobilier",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="TS Immobilier",
    directeur="Fofana César",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df = ajouter_these(
    df=df,
    nom="KOBRON",
    prenom="Ehien",
    impertant="KOBRON Ehien",
    contact="",
    theme="Evolution de la satisfaction clientèle particuluier à l'offre bancaire de prêt immobilier: Cas de la BHCI",
    thematique="Audit et contrôle",
    domaine="Audit et contrôle",
    filiere="Audit et contrôle",
    entite="BHCI",
    directeur="KOUASSI Rufin Cyriaque",
    date_depot="03/07/23",  # Format JJ/MM/AAAA
    date_soutenance="",  # Format AAAA-MM-JJ
    mentions=""
)
df.tail(5)

In [ ]:
df.to_excel("bd1.xlsx", index=False)