In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('bd1-1.xlsx', sheet_name='Sheet1')
df.tail(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
181,2025-04-15 00:00:00,MOUNDIN,Moumbagna Aboubakar Sidick,MOUNDIN Moumbagna Aboubakar Sidick,0152240877,Stratégie de conquête des clients par AFGBANK CI,Satisfaction clientèle,Satisfaction clientèle,Banque et assurance,AFG BANK,KONAN Amoin Lucie,NaN,NaN
182,2025-04-15 00:00:00,YABO,Ossondoh Martial,YABO Ossondoh Martial,NaN,Analyse des risques opérationnels bancaires da...,Gestion des risques,Gestion des risques bancaires,Banque et assurance,AFG BANK,N'GUESSAN Simon,NaN,NaN
183,2025-04-16 00:00:00,MIAKO,Jean Yves Arnold,MIAKO Jean Yves Arnold,0103926375,Effet de la croissance économique sur les inég...,Inégalité de Revenu,Bien être et pauvreté,Economie du développement,NaN,ASSOUMOU Giscard,NaN,NaN
184,2025-04-17 00:00:00,GNAMBA,Grâce Juvenal,GNAMBA Grâce Juvenal,NaN,Investissements directs étrangers et croissanc...,Investissement International; Mouvements de Ca...,Economie internationale,Economie du développement,NaN,AKA Brou,NaN,NaN
185,2025-04-17 00:00:00,SENY,Mariam Leka,SENY Mariam Leka,0777918656,Mise en place d'un système de pilotage de la p...,Système de pilotage de performance,Audit et contrôle interne,Audit et contrôle,GIH-UEMOA,KONAN Lucie,NaN,NaN

In [3]:
df.head(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
0,2020-10-19 00:00:00,NITIEMA,Wondpagnande Marceline,NITIEMA Wondpagnande Marceline,NaN,Mise en place d'une comptablité générale dans ...,Comptabilité générale,Comptabilité et gestion financière,Audit et contrôle,ALPHA,NaN,2020-11-11 00:00:00,Très Bien
1,2020-10-19 00:00:00,EVILARO,Grâce Ursula Aye,EVILARO Grâce Ursula Aye,NaN,Audit interne dans la performance finiancère d...,Audit interne,Audit et contrôle interne,Audit et contrôle,SIDAM SA,NaN,2020-11-11 00:00:00,Bien
2,2020-10-16 00:00:00,WABULASA,Kyalemaninwa Faustin,WABULASA Kyalemaninwa Faustin,NaN,Mise à jour du manuel de procédures de cycle d...,Optimisation des processus de trésorérie,Conformité réglementaire,Audit et contrôle,Caritas CI,NaN,2020-12-22 00:00:00,Bien
3,2020-10-16 00:00:00,NDIAYE,Fatou Raissa Inny Immaculee,NDIAYE Fatou Inny Immaculee,NaN,Evaluation du contrôle interne au niveau du cy...,Contrôle interne,Audit et contrôle interne,Audit et contrôle,epsilon,NaN,2020-12-22 00:00:00,Très Bien
4,2020-12-01 00:00:00,BATIONO,Marie Prudence Karidja,BATIONO Marie Prudence Karidja,NaN,La gestion du risque opérationnel de la caisse...,Gestion des risques,Gestion des risques,Audit et contrôle,AEB-CI,NaN,2020-12-21 00:00:00,Bien

In [4]:
promo_2020 = pd.read_excel('bd1-1.xlsx', sheet_name='2020')
promo_2020.head(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
0,2020-10-19,NITIEMA,Wondpagnande Marceline,NITIEMA Wondpagnande Marceline,NaN,Mise en place d'une comptablité générale dans ...,Comptabilité générale,Comptabilité et gestion financière,Audit et contrôle,ALPHA,NaN,2020-11-11,Très Bien
1,2020-10-19,EVILARO,Grâce Ursula Aye,EVILARO Grâce Ursula Aye,NaN,Audit interne dans la performance finiancère d...,Audit interne,Audit et contrôle interne,Audit et contrôle,SIDAM SA,NaN,2020-11-11,Bien
2,2020-10-16,WABULASA,Kyalemaninwa Faustin,WABULASA Kyalemaninwa Faustin,NaN,Mise à jour du manuel de procédures de cycle d...,Optimisation des processus de trésorérie,Conformité réglementaire,Audit et contrôle,Caritas CI,NaN,2020-12-22,Bien
3,2020-10-16,NDIAYE,Fatou Raissa Inny Immaculee,NDIAYE Fatou Inny Immaculee,NaN,Evaluation du contrôle interne au niveau du cy...,Contrôle interne,Audit et contrôle interne,Audit et contrôle,epsilon,NaN,2020-12-22,Très Bien
4,2020-12-01,BATIONO,Marie Prudence Karidja,BATIONO Marie Prudence Karidja,NaN,La gestion du risque opérationnel de la caisse...,Gestion des risques,Gestion des risques,Audit et contrôle,AEB-CI,NaN,2020-12-21,Bien

In [5]:
nombre_ligne = len(promo_2020)
nombre_ligne

8

In [6]:
promo_2021 = pd.read_excel('bd1-1.xlsx', sheet_name='2021')
promo_2021.head(5)

,Date de dépôt,Nom,Prenom,Impétrant,Contact,Thème,Thématique,Domaine,Filière,Entité,Directeur,Date de soutenance,Mentions
0,2021-01-05 00:00:00,DRABO,Fatoumata,DRAGO Fatoumata,NaN,Analyse de la politique de vente du produit fi...,Politique de vente,Conformité réglementaire,Banque et assurance,Loyale vie,NaN,2021-05-07 00:00:00,Bien
1,2021-01-05 00:00:00,OSSEY,Kopoin Jean Martial. E,OSSEY Kopoin Jean Martial,NaN,Financement des PME à la SIB analyse des diffi...,Financement des PME,Financement des entreprises,Banque et assurance,SIB,NaN,2021-05-11 00:00:00,Bien
2,2021-02-09 00:00:00,KDEA,Esther Marie-Noelle,KDEA Esther Marie-Noelle,NaN,Effet de la consommation des énergies renouvel...,Environnement et croissance,Croissance économique et productivité globale,Economie du développement,NaN,NaN,2021-05-11 00:00:00,Très Bien
3,2021-03-15 00:00:00,FOFANA,Bala Fatim Georgia,FOFANA Bala Fatim Georgia,NaN,Analyse de la chaîne de valeur du manioc dans ...,Analyse de la chaîne de valeur,Audit et contrôle interne,Audit et contrôle,Scoop-ca,NaN,2021-05-06 00:00:00,Très Bien
4,2021-03-31 00:00:00,KANGA,Ange Leandre,KANGA Ange Leandre,NaN,Analyse de la gestion de la relation client da...,Relation client,Bancassurance,Audit et contrôle,SOCIETE GENERALE,NaN,2021-05-18 00:00:00,Bien

In [7]:
nombre_ligne = len(promo_2021)
nombre_ligne

50

In [8]:
promo_2022 = pd.read_excel('bd1-1.xlsx', sheet_name='2022')
nombre_ligne = len(promo_2022)
nombre_ligne

15

In [9]:
promo_2023 = pd.read_excel('bd1-1.xlsx', sheet_name='2023')
nombre_ligne = len(promo_2023)
nombre_ligne

33

In [10]:
promo_2024 = pd.read_excel('bd1-1.xlsx', sheet_name='2024')
nombre_ligne = len(promo_2024)
nombre_ligne

52

In [12]:
promo_20245 = pd.read_excel('bd1-1.xlsx', sheet_name='2025')
nombre_ligne = len(promo_20245)
nombre_ligne

28